base:
  random_state: 42

data_load:
   dataset_csv: 'data/raw/iris.csv'
   features_path: 'data/processed/features_iris.csv'
   trainset_path: 'data/processed/train_iris.csv'
   testset_path: 'data/processed/test_iris.csv'
   test_size: 0.2

train:
  #training, hyperparameters
  clf_params: 
    'C': 0.001
    'solver': 'lbfgs'
    'multi_class': 'multinomial'
    'max_iter': 100
  model_path: 'models/model.joblib'



reports:
 #metrics,images,etc..
  metrics_file: 'reports/metrics.json'